name = "FallingTree"
filename = "FallingTree-1.18.1-3.2.0b2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Fb4jn8m6/versions/1.18.1-3.2.0b2/FallingTree-1.18.1-3.2.0b2.jar"
hash-format = "sha1"
hash = "cf6c84876c1e42da3dbd593de70116d7d6129ce2"

[update]
[update.modrinth]
mod-id = "Fb4jn8m6"
version = "UiUNxrl7"
