name = "Trinkets (Fabric)"
filename = "trinkets-3.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/559/trinkets-3.2.0.jar"
hash-format = "sha1"
hash = "4a31e5b5a00f44907d5f8f59c2c1b2501d92bb8e"

[update]
[update.curseforge]
file-id = 3629559
project-id = 341284
